### ISSUE TITLE
Album cover art import support

### ISSUE THREAD

**Issue by weilbith** [hellricer/cursedtag#1]
This looks already pretty great. I'm using EasyTag so far, which you references as inspiration. And also the feature sets looks pretty similar. I would love to switch to this here, since I'm living in the console. But what I really miss is the support to import album covers. It is a must for me to have my `.mp3`'s to have included arts. I don't need them to be previewed, but the option to import them by editing a tag as any other and also apply it for the current selection.
Do you think this is a reasonable feature?

**Comment by hellricer** [comment]
Hey, thanks for checking it out!

I'm not quite sure what the use-case would be? Would you like to just enter the filename in the editor? Because I'm not sure I'd want to introduce browser for choosing the image.  

Besides, it's quite common to have multiple images in on file. Furthermore, there are special sub-fields like type & description...

**Comment by weilbith** [comment]
Yes, I would vote for a simple insertion of a file path. If it would include tabbing to complete, it would be awesome. Browser seems not necessary for me. of cause you could start ranger etc, but this must then be configurable if someone wants to use MC, or... So I guess text-only would be fine to not bloat it up.

Hmm. That is also true. Maybe start little? :thinking: :smile:

**Comment by weilbith** [comment]
I wanted to edit some tags of new music to day. Have to use EasyTag for the images. It bothers me to have two tools doing the same. 😝
So do you consider to add such feature or can this be closed anyway?

**Comment by hellricer** [comment]
Hey, I definitely plan to add support for images, but I want to do it right - simply adding new field into editor view would be a) incomplete and b) wouldn't play nice with current implementation.

I'm now focusing on bugs & features that scratch my own itches, but I'm giving this feature-request highest priority otherwise.

**Comment by hellricer** [comment]
I tried to came up with basic concept for cover-art manager. 
You can find it on [feature/coveart-manager-concept](https://github.com/hellricer/cursedtag/tree/feature/coverart-manager-concept) branch.

You can start it with `i`, and then `a` for add, `d` for delete & `s` for save.

Problems:
  * Only mp3 files are supported for now, because vorbiscomment and metaflac
    have quite hard-to-parse outputs when it comes to images...
    But there [seem to be some efforts](https://superuser.com/questions/169151/embed-album-art-in-ogg-through-command-line-in-linux) that we might re-use.

  * mid3v2 only provides `--delete-frames=APIC`, which deletes all images at once... 
    For now, UI reflects this behaviour until workaround will be found.

Bear in mind that it's really just a concept, that will need lot of refactoring, before (if?) it will be merged...

**Comment by weilbith** [comment]
Sound pretty nice when reading it. So far I wasn't using it, because of this missing feature. So I just "installed" it (probably will build an AUR package) to test this cool stuff. Unfortunately I must open issue #3. Afterwards I'm happy to try it out. :+1:

**Comment by weilbith** [comment]
Okay, first feedback:
- I can delete files and make this change permanent.
- I can't add new images at all (also if I deleted the existing one with save or without). I just get back to the folder and see no files anymore. The `.mp3` file does not appear again until I restart _cursedtag_. Funny point: if I go back from here to the parent directory, it is sorted desc now.

**Comment by weilbith** [comment]
I think the feature is good enough to close this issue. Any improvements to it should result into new issues. :+1:
